apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
{{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
{{- end }}
          volumeMounts:
{{- range .Values.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath | quote }}
{{- if .subPath }}
              subPath: {{ .subPath | quote }}
{{- end }}
{{- if .readOnly }}
              readOnly: true
{{- end }}
{{- end }}

      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}

      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}

      volumes:
{{- range .Values.volumes }}
        - name: {{ .name }}
{{- if .secret }}
          secret:
            secretName: {{ .secret.secretName }}
{{- end }}
{{- end }}
